spring:
  application:
    name: learning-kotlin
  datasource:
    url: jdbc:mysql://localhost:3306/lk
    username: root
    password: "SpygzQ0D$50A%w5:"
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

springdoc:
  api-docs:
    path: /v3/api-docs
  swagger-ui:
    path: /swagger-ui.html
logging:
  level:
    com.zaxxer.hikari: DEBUG
    org.hibernate.sql: DEBUG
jwt:
  secret: MySuperSecretJwtKeyThatIsLongEnough123!
  expiration: 36000000000